spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: 123456

  mail:
    username: 2718458328@qq.com
    password: cymiuegpgozhdfeh
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true


server:
  port: 9090

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
  type-aliases-package: com.zwj.pojo
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.zwj.mapper: debug
    com.zwj.exception: error



